### ISSUE TITLE
mounting into /app overwrites the jtcl binary

### ISSUE THREAD

**Issue by ernst-at-tv2** [joxz/docker-testcl#1]
when we mount our outside directory into /app we also in turn override the jtcl binary. So we end up with an `su-exec: jtcl: No such file or directory` error when running the container with `docker run -it --rm -v $(pwd)/test:/app docker-testcl:latest jtcl /app/test_devops-1983.tcl`

**Comment by joxz** [comment]
Seems like i shot myself in the foot by moving everything to /app. I'll take a look!

**Comment by ernst-at-tv2** [comment]
The easy fix is just to recommend that people mount into `/app/test` instead of `/app` then it works fine 👍

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by joxz** [comment]
I commited a fix to https://github.com/joxz/docker-testcl/compare/dirfix
Could you please test? Worked fine for me:

```
PS> docker run --rm -it -v D:\docker-testcl\test:/app jones2748/docker-testcl:latest jtcl test_jtcl_irule.tcl
The jtcl-irule extension has successfully been installed
```

**Comment by ernst-at-tv2** [comment]
@joxz 👍 works fine now! and also great job! appreciate that I don't have to build my own container for TesTcl 🙂

**Comment by joxz** [comment]
np at all! happy to share
